# server configuration
server: 
  example: # server name
    source: http://192.168.3.1:8888 # required
    auth: false # optional, default to false
    auth_header: Authorization # optional
    auth_password: Bearer test # optional
    fetch_interval: 10 # required
    data_type: 1
    ssh: 
      enabled: false
      host: 10.0.0.1:22 # server:port
      use_key: false
      user: root
      password: test
      key: ~/.ssh/id_rsa # must have use_key enabled to take effect
    remote: example.com:443 # required
    password: test # required
    tls: true # optional, default to false
    insecure: false # optional, default to false
    report_delay: 1 # optional, default to 1
# nezha-agent fields
debug: true
ip_query: true
use_ipv6_countrycode: false
dns: []
