# server configuration
servers:
  example: # server name
    source: http://192.168.3.1:8888 # required if using HTTP
    source_type: 2 # 1->HTTP, 2->TCP
    auth: false # optional, default to false
    auth_header: Authorization # optional
    auth_password: Bearer test # optional
    fetch_interval: 10 # required
    data_type: 1 # required. view pkg/monitor/monitor.go for details
    version_suffix: -broker # optional, default "-broker"
    ssh:
      enabled: false
      host: 10.0.0.1:22 # server:port
      use_key: false
      user: root
      password: test
      key: ~/.ssh/id_rsa # must have use_key enabled to take effect
    remote: example.com:443 # required
    agent_secret: test # required
    uuid: 00000000-0000-0000-0000-000000000000 # required
    tls: false # optional, default to false
    insecure: false # optional, default to false
    report_delay: 1 # optional, default to 3
  # add more servers if you like
  # example2
  #   ...

# broker options
debug: false
ip_query: false
use_ipv6_countrycode: false
listen_addr: 0.0.0.0:8088 # required
dns: []
