name: Release

on:
  workflow_dispatch:
  release:
    types: [published]
  
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        goarch: [amd64, 386, arm64, riscv64, arm]
    
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
        
      - name: Build
        run: |
          mkdir build
          go build -o build/broker -ldflags '-s -w' -trimpath ./cmd/broker
          cp example/config.yml build
      
      - name: Create zip archive
        if: github.event_name == 'release'
        run: |
          cd build
          zip -9vr ../broker_${{ env.GOOS }}_${{ env.GOARCH }}.zip .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: broker_${{ env.GOOS }}_${{ env.GOARCH }}.zip
          path: |
            ./broker_${{ env.GOOS }}_${{ env.GOARCH }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: '**'
          path: ./archives

      - name: Checksums
        shell: bash
        run: |
          find ./archives -type f -name "*.zip" | while IFS= read -r archive; do
            openssl dgst -sha256 $archive | sed -E 's/SHA2-256\(([^)]+)\)= (.+)/\2 \1/' >> checksums.txt
          done
      
      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./archives/broker_*.zip
          tag: ${{ github.ref }}
          file_glob: true
